// 广度优先搜索
import './test/BFS'
// 深度优先搜索
import './test/DFS'
// Dijkstra算法
import './test/Dijkstra'
// Floyd-Warshall算法
import './test/Floyd-Warshall'
// Prim算法
import './test/Prim'
// Kruskal算法
import './test/Kruskal'
